### ISSUE TITLE
Handle more then one test execution

### ISSUE THREAD

**Issue by RMadjev** [kiwitcms/phpunit-plugin#28]
[TestExecutionRepository.php](https://github.com/kiwitcms/phpunit-plugin/pull/27/files/083ba29c9ce18f79e9c73f960231773001708d26..b4fd837bd6fe9abf2d44b6dc01a348c69060d7b9#diff-21a369f3d498099fcd2a2c62d1411cbca390330e4aa8c7059fb4adb03194f2ae)

If test executions are more then one, create them.

**Comment by RMadjev** [comment]
When I follow the code I found out that there is nothing wrong. The method we modified is "create" and the response will always contains only one element. IMO nothing to do here.

**Comment by atodorov** [comment]
The `TestRun.add_case()` API method returns a list of TestExecution objects. If the TC or TR have defined prooperties/environment then there will be more than 1 TE created for the same TC, see https://kiwitcms.org/blog/atodorov/2022/01/24/properties-environments-and-test-matrix-generation/ for context.

Then inside the `createTestExecution()` function and everywhere it gets used you need to account for the fact that now you have a list of objects, not a single object.

On a side note: `createTestExecution`, `updateOrCreateTestExecution` and  `createTestCaseAndTestExecution` seem to be very close in implementation. I haven't looked at them in details but it looks like all of these functions are doing more than one thing at the same time, iow their scope is unnecessarily broad.

**Comment by RMadjev** [comment]
Fixed in https://github.com/kiwitcms/phpunit-plugin/pull/37
